#!/bin/sh

# import './hardware-configuration.nix' not working with symbolic link
sudo ln -i -s $(pwd)/machines/nixos/configuration.nix /etc/nixos/ &
sudo nixos-rebuild switch

ln -i -s $(pwd)/users/gbrlmarn/home.nix ~/.config/home-manager/ &
home-manager switch
