#!/bin/sh

# import './hardware-configuration.nix' not working with symbolic link
sudo ln -i $(pwd)/configuration.nix /etc/nixos/
sudo nixos-rebuild switch

ln -i -s $(pwd)/home.nix ~/.config/home-manager/
home-manager switch
